flowchart BT
  subgraph Algorithms
    direction BT
    subgraph Sklearn
    direction BT
        OPTICS
        SpectralClustering
    end
    KMeans --> A
    KMeans --> B
    subgraph ImprovedKMeans
        A
        B
    end
    Sklearn & ImprovedKMeans ~~~ Implementations & ResultsData
  end
  subgraph Analysis
  direction BT
    StatisticalAnalysis --> Plots
    Tables
  end
  subgraph Report
  direction LR
    Methods
    Results --> Discussion
  end
  subgraph Infrastructure
  direction BT
    MakeFile
    DataConfig
  end
  Algorithms --> ResultsData
  ResultsData ==> Analysis
  Data --> Preprocessing --> Algorithms
  Implementations & Preprocessing ==> Methods
  Plots & Tables ==> Results
  MakeFile
  DataConfig
  Infrastructure --> Preprocessing
  Infrastructure --> Analysis
